from typing import Protocol, Dict

class Demodulator(Protocol):
    def config_init(self):
        ...
    def set_all(self, freq: float, symrate: float) -> None:
        ...
    def switch_rx1(self) -> None:
        ...
    def switch_rx2(self) -> None:
        ...
    def is_locked(self) -> bool:
        ...
    def get_esno(self) -> float:
        ...
    def get_packet_traffic(self) -> float:
        ...
    def reset_counters(self) -> None:
        ...
    def get_general_info(self) -> dict:
        ...